// Generated by gencpp from file robocup_control/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROBOCUP_CONTROL_MESSAGE_ADDTWOINTS_H
#define ROBOCUP_CONTROL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <robocup_control/AddTwoIntsRequest.h>
#include <robocup_control/AddTwoIntsResponse.h>


namespace robocup_control
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace robocup_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robocup_control::AddTwoInts > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::robocup_control::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::robocup_control::AddTwoInts > {
  static const char* value()
  {
    return "robocup_control/AddTwoInts";
  }

  static const char* value(const ::robocup_control::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::robocup_control::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::robocup_control::AddTwoInts >
template<>
struct MD5Sum< ::robocup_control::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robocup_control::AddTwoInts >::value();
  }
  static const char* value(const ::robocup_control::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robocup_control::AddTwoIntsRequest> should match
// service_traits::DataType< ::robocup_control::AddTwoInts >
template<>
struct DataType< ::robocup_control::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::robocup_control::AddTwoInts >::value();
  }
  static const char* value(const ::robocup_control::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robocup_control::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::robocup_control::AddTwoInts >
template<>
struct MD5Sum< ::robocup_control::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robocup_control::AddTwoInts >::value();
  }
  static const char* value(const ::robocup_control::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robocup_control::AddTwoIntsResponse> should match
// service_traits::DataType< ::robocup_control::AddTwoInts >
template<>
struct DataType< ::robocup_control::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::robocup_control::AddTwoInts >::value();
  }
  static const char* value(const ::robocup_control::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCUP_CONTROL_MESSAGE_ADDTWOINTS_H
