// Generated by gencpp from file robocup_control/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef ROBOCUP_CONTROL_MESSAGE_ADDTWOINTSRESPONSE_H
#define ROBOCUP_CONTROL_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robocup_control
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : Sum(0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : Sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _Sum_type;
  _Sum_type Sum;





  typedef boost::shared_ptr< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::robocup_control::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::robocup_control::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::robocup_control::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Sum == rhs.Sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robocup_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "055d509888d173367b1b9f94491341fd";
  }

  static const char* value(const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x055d509888d17336ULL;
  static const uint64_t static_value2 = 0x7b1b9f94491341fdULL;
};

template<class ContainerAllocator>
struct DataType< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocup_control/AddTwoIntsResponse";
  }

  static const char* value(const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Sum   \n"
;
  }

  static const char* value(const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robocup_control::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robocup_control::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "Sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCUP_CONTROL_MESSAGE_ADDTWOINTSRESPONSE_H
